services:
  rag_service_csc207:
    build: ./backend/rag_service
    environment:
      - NEO4J_URI=neo4j+s://9a5c6af1.databases.neo4j.io
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=LImqHXRqouoA7sJXBsDaXK9WlmPT25up2E8rrcCopLY
      - OPENAI_API_KEY=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
    networks:
      - internal_network

#  rag_service_csc311:
#    build: ./backend/rag_service
#    environment:
#      - NEO4J_URI=uri
#      - NEO4J_USERNAME=neo4j
#      - NEO4J_PASSWORD=password
#      - OPENAI_API_KEY=key
#    networks:
#      - internal_network

  backend_service:
    build: ./backend
    ports:
      - "7001:7001"
#    volumes:
#      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=sqlite:///database.db
      - JWT_SECRET_KEY=.8Pte>wy5'?rC*c
      - VALID_API_KEY=R6JV8jeiZx
      - RAG_SERVICE_CSC207_URL=http://rag_service_CSC207:6000
      # - RAG_SERVICE_311207_URL=http://rag_service_CSC311:6000
      - CSC207_FLOWCHART=assets/CSC207_flowchart.json
    depends_on:
      - rag_service_csc207
      # - rag_service_csc311
    networks:
      - internal_network

  # frontend_service:
  #   build: ./src
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend_service
  #   command: npm run start

networks:
  internal_network:
    driver: bridge