services:
  rag_service_csc207:
    build: ./backend/rag_service
    environment:
      - NEO4J_URI=neo4j+s://uri
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=key
    networks:
      - internal_network

#  rag_service_csc311:
#    build: ./backend/rag_service
#    environment:
#      - NEO4J_URI=neo4j+s://uri
#      - NEO4J_USERNAME=neo4j
#      - NEO4J_PASSWORD=password
#      - OPENAI_API_KEY=key
#    networks:
#      - internal_network

  backend_service:
    build: ./backend
    ports:
      - "7000:7000"
#    volumes:
#      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URI=sqlite:///database.db
      - JWT_SECRET_KEY=secret
      - VALID_API_KEY=key
      - RAG_SERVICE_CSC207_URL=http://rag_service_CSC207:6000
      # - RAG_SERVICE_311207_URL=http://rag_service_CSC311:6000
      - CSC207_FLOWCHART=assets/CSC207_flowchart.json
    depends_on:
      - rag_service_csc207
      # - rag_service_csc311
    networks:
      - internal_network

  frontend_service:
    build: ./src
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend_service
    command: npm run start

networks:
  internal_network:
    driver: bridge